spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost}:9092

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVICE_SERVERS:localhost}:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
